sudo: false
language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
script:
  - scripts/build-ci
after_success:
  - scripts/coveralls
after_success:
  - scripts/travis-ci-bintray-credentials
  - scripts/travis-ci-artifactory-credentials
  - scripts/publish
notifications:
  email: false
env:
  global:
  - secure: Koh9OjIn10Tj5nAs12blTZksTfB8cXtgHsf2lRxs5PTrgdfjpBtFsL/Jp1Ougav8INByvnyeXwO0SePC9xxVYjpU7RkawO0wYj0pQOXU1D6rIzKjeKpEJoTMuaYiL1q2CsXujYP7MF+FidzNA0zVtZmednUZroKqA/QvcwXWK+KKmaNOrh8rH54daE8yLxsM8iOz/Up9fDAFrQGQ8hYpuYqYBSJZ8mLygLcw4MP9psGvha2vbM9XTNtHCwPo3fJF/NyCm+LtiLsjACCZi04kLPEOtpTvQEiYf9FyvzYSonTZYGltj3dcwa3f0FN/kCEtwU0jgTE7FoktaZlt+B+M3+rvCuc0mwdPJoww+nWCWJfBwah3HLXvW8b6RbtEslk45Zka4KxYct7kifIEzYd0Lh/YmLSzKg8nFnGodtm/mQVItEX5EUwOOTEc+oecHapHBQcLRhwUS9rSrYpgDZTw2wnJfUokx1FaWwdhDYLbNL6V7FUjg8thrjHCv5wgi3LXCd/urlmaR+GJztY9uQhrSBoqCf0Qqoi1unWb8rTOFN91zCNPMkqd3NA6TfTz0atXtqG4hrqa1qZZY0s1KIBSrvrK1k+Ha2xlRceiq3WBOUzjLV7X1LpVOHEL/6QAiUPI6C1GKxZCVNWTka2ZpGrYgsMJ/VYkHE3zbcDWdtwqEG0=
  - secure: Nqt9ucUgA1yPpN2v/POPLkGoN3gAvlPAbgEYL7RCkRrP58wW5KImqsXjwaiE08ZCQLv1Tz6h72weHbSOIKt/PtxPw0yE9cDLER8llgUJUdjxARfQcNxHPp7Aol6eZe4XdAkvUAt1aXnLcHOIlOsBvcpSlD4+UXNKSwApTDmjr/UeDN18EeyrLNA5XtlJceofxvj1/HxZItYvXH8ednZIeO2U/YjCB9CIyss+H8IDS8ayNamcw5PXFmwFlb2OoWio3uo1q7+DUw5Yg7tiKvoZkRqPc8sNioisKSLy6JSMQfC97IGJ36Tr4s1nbpyyE93yGJUeBpd/SMfB/yUjNYTN/RlN3ISZDGcDj3haBI6Y0ON2oyrbNEpQ34Ny9pqmnb2bj5+qpJ4Gv/b01pbt6CUEYNSAhkJ7gok09lBG4yEb1vF5KxCdj29NUUEjH+qSVzdjeKzTZMXQuvl32iVy1o4UDcxDdH5WkTxLlwJm8AarkdnV8y3tpRxQPpdONPPlinyjx6M0x5yfM+BKTpGe6weRA2Z/5k5otacJRR0FJjwHORYugnoe/qI7aE7BHUyLvHO1EQc55RPe1fnxj0s3hEwM4kPXjOdocfJyTweIS9q1p1ubolTVdxa6rG5xnk12NooGIzstV6K0NIinNi193fOpKPti5As8YauGgM+iXO6Jw3g=
